from physical_layer import PhysicalLayer
from data_link_layer import DataLinkLayer
from network_layer import NetworkLayer
from transport_layer import TransportLayer
from session_layer import SessionLayer
from presentation_layer import PresentationLayer
from application_layer import ApplicationLayer
# Initialize Layers
phys_layer = PhysicalLayer()
datalink_layer = DataLinkLayer()
net_layer = NetworkLayer()
trans_layer = TransportLayer()
sess_layer = SessionLayer()
pres_layer = PresentationLayer()
app_layer = ApplicationLayer()
# Prompt user for message input
data = input("Enter the message to send: ")
print(f"\nOriginal Message:\n{data}\n\n")
# Sending Process (Top to Bottom)
print("=== SENDING PROCESS ===\n")
data = app_layer.send(data)
print(f"Application Layer (send):\n{data}\n\n")
data = pres_layer.send(data)
print(f"Presentation Layer (send):\n{data}\n\n")
data = sess_layer.send(data)
print(f"Session Layer (send):\n{data}\n\n")
data = trans_layer.send(data)
print(f"Transport Layer (send):\n{data}\n\n")
data = net_layer.send(data)
print(f"Network Layer (send):\n{data}\n\n")
data = datalink_layer.send(data)
print(f"Data Link Layer (send):\n{data}\n\n")
data = phys_layer.send(data)
print(f"Physical Layer (send):\n{data}\n\n")
print("Data Sent Successfully!\n\n")
# Receiving Process (Bottom to Top)
print("=== RECEIVING PROCESS ===\n")
data = phys_layer.receive(data)
print(f"Physical Layer (receive):\n{data}\n\n")
data = datalink_layer.receive(data)
print(f"Data Link Layer (receive):\n{data}\n\n")
data = net_layer.receive(data)
print(f"Network Layer (receive):\n{data}\n\n")
data = trans_layer.receive(data)
print(f"Transport Layer (receive):\n{data}\n\n")
data = sess_layer.receive(data)
print(f"Session Layer (receive):\n{data}\n\n")
data = pres_layer.receive(data)
print(f"Presentation Layer (receive):\n{data}\n\n")
data = app_layer.receive(data)
print(f"Application Layer (receive):\n{data}\n\n")
print("Data Received Successfully!\n")
